name: ai_plant_app
description: AI Plant Identification & Plant Care Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  camera: ^0.11.2
  permission_handler: ^11.4.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  logger: ^2.5.0
  connectivity_plus: ^6.1.3
  lottie: ^3.3.3
  local_auth: ^2.3.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/home/trending/
    - assets/images/home/categories/
    - assets/images/home/remedies/
    - assets/images/home/tips/
    - assets/images/home/quiz/
    - assets/images/home/diseases/
    - assets/images/home/suggestions/
    - assets/images/home/premium/
    - assets/images/garden/soil/
    - assets/icons/
    - assets/icons/social/
    - assets/icons/tools/
    - assets/svg/
    - assets/animations/
    - assets/lottie/
